name: "Bateau Elorn"
description: "Blog de la vie à bord et de l'aménagement du bateau Élorn"
markdown: redcarpet
pygments: true
author: "F. Fleutot"
url: "http://fab13n.github.io/elorn"
baseurl: "file:///home/fabien/Dropbox/elorn/site/_site"